//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_attributes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: i32,
    #[sea_orm(unique)]
    pub display: String,
    pub created_at: DateTimeWithTimeZone,
    pub last_login: Option<DateTimeWithTimeZone>,
    pub last_updated: DateTimeWithTimeZone,
    pub settings: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_email_password::Entity",
        from = "Column::Uid",
        to = "super::user_email_password::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserEmailPassword,
}

impl Related<super::user_email_password::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEmailPassword.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
